export const homeData = [
    {
      id: 1,
      name: "",
      rating: "",
      time: "",
      desc: "",
      starring: "",
      genres: "",
      tags: "",
      cover: "https://apianoyes.vn/wp-content/uploads/2022/01/slide-tet-2022.png",
      date: "",
    },
    {
      id: 2,
      name: "",
      rating: "",
      time: "",
      desc: "",
      starring: "",
      genres: "",
      tags: "",
      cover: "https://pianohcm.com/wp-content/uploads/2020/03/Banner-Pianoht-2020-scaled.jpg",
      date: "",
    },
    {
      id: 3,
      name: "",
      rating: "",
      time: "",
      desc: "",
      starring: "",
      genres: "",
      tags: "",
      cover: "https://pianohcm.com/wp-content/uploads/2020/03/Banner-Pianoht-2020-scaled.jpg",
      date: "",
    },
    {
      id: 4,
      name: "",
      rating: "",
      time: "",
      desc: "",
      starring: "",
      genres: "",
      tags: "",
      cover: "https://pianohcm.com/wp-content/uploads/2020/03/Banner-Pianoht-2020-scaled.jpg",
      date: "",
    },
  ]
  
  