const NewsApi = [
    {
      id: 1,
      image: "https://c4.wallpaperflare.com/wallpaper/36/378/566/music-guitar-shop-wallpaper-preview.jpg",
      date: "26 Jun, 2022",
      title_one: "TikToker review Universe 9 Danang branch.",
      desc_one: "On the evening of January 26, the famous TikToker association came to Universe 9 branch to experience the restaurant's dishes and services and gave endless compliments to the restaurant. The TikTokers gave a very honest opinion about the food and encouraged people to come and experience it.",
      title_two: "",
      desc_two: "",
      title_three: "",
      desc_three: "",
    },
    {
      id: 2,
      date: "18 April, 2022",
      image: "https://www.steinwaypianos.com/.imaging/mte/steinway-us-theme/Large-Rectangle/dam/steinwaypianos.com/locations/Steinway-Piano-Store.jpg/jcr:content/Steinway%20Piano%20Store.jpg",
      title_one: "The restaurant's variety of special dishes makes people wobble.",
      desc_one: "On the evening of January 26, the famous TikToker association came to Universe 9 branch to experience the restaurant's dishes and services and gave endless compliments to the restaurant. The TikTokers gave a very honest opinion about the food and encouraged people to come and experience it.",
      title_two: "",
      desc_two: "",
      title_three: "",
      desc_three: "",
    },
    {
      id: 3,
      image: "https://i2-prod.manchestereveningnews.co.uk/incoming/article23135133.ece/ALTERNATES/s1200b/1_DBR_MEN_1502222Piano_25jpeg.jpg",
      date: "10 Mar, 2022",
      title_one: "Hot TikToker excellent review of food, from service to facilities.",
      desc_one: "On the evening of January 26, the famous TikToker association came to Universe 9 branch to experience the restaurant's dishes and services and gave endless compliments to the restaurant. The TikTokers gave a very honest opinion about the food and encouraged people to come and experience it.",
      title_two: "",
      desc_two: "",
      title_three: "",
      desc_three: "",
    },
    {
      id: 4,
      image: "https://assets.classicfm.com/2015/10/violin-shop-tampa-1426003776-view-0.jpg",
      date: "06 Feb, 2022",
      title_one: "The restaurant's variety of special dishes makes people wobble.",
      desc_one: "On the evening of January 26, the famous TikToker association came to Universe 9 branch to experience the restaurant's dishes and services and gave endless compliments to the restaurant. The TikTokers gave a very honest opinion about the food and encouraged people to come and experience it.",
      title_two: "",
      desc_two: "",
      title_three: "",
      desc_three: "",
    },
    {
      id: 5,
      image: "https://www.moseleyviolins.co.uk/wp-content/uploads/2020/09/Shop-July-20201.jpg",
      date: "01 Jan, 2022",
      title_one: "Bringing Japanese dishes to the menu, rain compliments from diners.",
      desc_one: "On the evening of January 26, the famous TikToker association came to Universe 9 branch to experience the restaurant's dishes and services and gave endless compliments to the restaurant. The TikTokers gave a very honest opinion about the food and encouraged people to come and experience it.",
      title_two: "",
      desc_two: "",
      title_three: "",
      desc_three: "",
    },
  ]
  export default NewsApi